command:
  - python
  - start_server.py

env:
  - name: MLFLOW_EXPERIMENT_ID
    valueFrom: experiment
  - name: AGENT_MODEL_ENDPOINT
    valueFrom: serving-endpoint
  - name: AGENT_UC_VOLUME_PATH
    valueFrom: uc-volume-write
  - name: AGENT_OUTPUT_MODE
    value: "uc_volume"
  - name: AGENT_SKILLS_DIR
    value: "./.claude/skills"
  - name: AGENT_MAX_ITERATIONS
    value: "10"
