# Databricks App configuration for the DOCX Skills Agent
# See: https://docs.databricks.com/aws/en/dev-tools/databricks-apps/configuration.html

name: docx-skills-agent
description: AI agent with document creation skills using python-docx

# App start command
command: ['python', 'start_server.py']

# Compute configuration
compute:
  size: medium  # Options: small, medium, large

